### ISSUE TITLE
Add a display of team information on the Home Page

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#17]
Display
```
Team Members: # (links to Team Page)
Unique Skills: # (links to Skills Page)+
Recent Skill Events: List Last 5 TM_Skill and/or Skill Reviews"
```

**Comment by Hopding** [comment]
In the process of implementing this, I noticed that we are not collecting any timestamp data for TMSkills. As such, it isn't possible to list "recent" TMSkill events. So I won't worry about that for this PR, but we may want to consider collecting TMSkill timestamps if this is something we are going to want to do in the future?

Note that we are collecting Skill Review timestamps, so that won't be an issue.
